# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93b55cc5bf2a702775ea858f695e788cea7fde44945f7ee7fd55d0957a52fb615086d5d52d01d55bfe0f3918d87fd6161f1a2dafb386965a94995aa6d1676863

test:
  secret_key_base: 4f7d7395e94270421f5630b6138aa2ec76ad670a1a76799f3b28af239de3243c100fe1cc3fbefdc10a9141155cfdd05d7a4a6d1746ba2e33cb1c41ee19f0f1d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
