#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:   &development_defaults
  key:         1234567890ABCDEF1234567890ABCDEF
  iv:          1234567890ABCDEF
  cipher_name: aes-128-cbc
  encoding:    :base64strict

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEApdrJFnxN9+eJycypS1Pdjsxir78lLHJFmKnU4L1JPSsUQO/a
    htSWmQLkwk/HOz8eZ9N9u1GhM55kJzwgv3zZgJZYA+9O/b2LIrOTPronJvOXjh08
    PdKYWF9T1WdiGSZx7WbTyStYckC85l+ca4Wh/35eQhTxehcP935f8aHGkCDL/NOD
    ttDJlnaq+nHY0pe2xF6kV/usvNqQhDQocxHyHs7/lXXKT8MzJKMrg3Q1cEumjhvX
    5JpnsS1ZcgwVl7vfZOzLXMHEfFgy0CzoQXQidXTgW+i7UnmWPjfTCzdUP8E3ZW/J
    H8p8ZRUTLPwWcZZ6h/9h4YaNuSaOe4ZxJjsD5wIDAQABAoIBADeqUsuFNPX7dDeS
    xU9O+pGu74Bk+ykLwWgXuCcl4KrzBn01A3c1asY4PmcpN4kfCil2xkBUiXI1uw+g
    Eq2yTZ3m1+uaKjznnQcslkL7X6CnKTq9fTaStCcU96IsbLRcPuibFoHyVmEicUQw
    2uMLmu+RjjlHpjSAAQ/kDnefAHHmxbgeA0tnVhkyOFHOZxlFmE2ltirrqaD+TPkc
    AV0DBBiP7Gspfr/l2nzyCEMMusCBvofqAwpqE+m33EMKa+H2NelAlxWuB65UztlX
    OCilSlIo8GcmtAlMvCaJ8VxdRqCS+PCrTIO5MxLuONHT9RPEZLAKlPh0xNxDYL4u
    HBE3rUECgYEA0iGRGqRkKw6jRbGgWE6cl/opIK3UGB7rsR+6kqkrmi8Tl7pB1q8Q
    giEMTPf3M+r13z0HrqkSrfm4n/Wz6vKpyQZ/8ruN+4sdLiTB/NkXmn1STgGCpyUN
    pZwhIGjZsJP6PQj3tQ4Yh3qs+Y4QZginpjqBwioVpczUpiUr3VY1Zq8CgYEAyg77
    41pF3nFiENXYVbx9REZMX9t6/67tFKgzEt4BtE3pEEyKGckldzVBnXMs9XLwxIz8
    wbEQ2KF8Mlo8VwGYcYcVjb6cg/H4PwXw4mC1saQ0+irUvzdr+DrasOKIbyL7tLiA
    3QHYy/JaLvEgNvQ0g+YmRucjeLGc2QDBJ/R6BEkCgYEAtl4nfwXZYX0MurnUPY/M
    XCHie9ghUOXVDB5LYGmty9y7ll0yMs4w958S++HhC5AJ37sp5a4a5h7q2vj1Mx1z
    uWIIvXOFYCB2LMv+CCGpWI0XV1f8Om/wDiEYpvYYqCVlcn9L7DjVlQ8k/FkNZmBw
    j9YLM6Yur3y7uY5dKXVeV0UCgYAG9jEzih6yJVHtppCHk7D1Mz7aZqN8P7inZ4wq
    8D86yRxolVqEvOtvigQyuo8n/cfR3dGvkrwz2ox+56EAlmt8Ld1OPu0Blsqo0TmV
    cyOPdUrl+6fM1sn/iXeTdJqiyZ/GgDzgYHnpvPXifChR/GP6z2kuNDSCqgvvZhlB
    mSjDEQKBgQCLftKKWHXhr/qTznPhYxu3NqBGiF09291NQE1Lyyefna6ZyHqSRvDK
    aMEImbyUIaSfqd+FYrc7XBuMTCe9w3snS0QftjLbYbOALZVR1zYq1X5IGDGlvh9c
    MCr21pWV6psF8mh9irDHWB2aQRdnG1OaT9aIKkWZubw5d/4U6sENxQ==
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/fiveguardoffense_release.key
      iv_filename:  /etc/rails/keys/fiveguardoffense_release.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEA3jVxQ6ijzMHonG9w9RVUdi5jTz4eOvcGTqZCiCxvc7QVAS1v
    7YfKlwr4G0FnFBYsNvrPA9s0qjSXFGAhAJZSUEMOat3XKdh0qznHDDF76ZsgMwJ3
    M+0FNKXG/hLdOWUpqC4FYiXBTKoZ/PVyIDZWLT2oC9GqVhJN7ATzBN9CA7AkFtML
    p0ZB25QKOoJBD7vTL5UzmwUe9ZzCMbxbkEOKZywIUdzRCdztWPRonDovqrLj/mEP
    2n2idAqg6A8m2TFNWlQ7NDJDEPyQSpJ7dA68ji3TNyU1fgyQRx6R+osjkpTeBLYH
    yNhDDnmdOJjJrvdPgB55jI8DkTzfc4zOTsz+EQIDAQABAoIBAQCKYwAiIfG5QH5M
    hr7zc5BBdcxVeps7H8Lm0naW9g2HInz+WbzeUnZiMOuplcbLZK+uoe6xOSCIa+43
    O1LyWavz3n8pIPWyUuL+DCKhvmOsbfbUrdFtHkzip+fRLhBmgVE7M0YZBOhohXtf
    5cBovU5YKJDyo2YQ6p9qwP5UZ3JmdnArPIn2pEVKapBT0ObsenBYCEOCJ6OQaZnm
    Rubye6nHKC+d1TjHql9S1izYYfC8MdvmqIv8sbh1j2UOruu54pP0KcEsvvWri2/n
    etJnY9Vl84DTzUif3BKyazp12zI8FWVXaZzhzgSrPCYUctqKZiKmPDQEkI/VKkH9
    Ji90v8udAoGBAPQQ+dDSCCw+1fWaTNOl5oZ2qLoFWOP+Lt7JjXlaagRDlmmVn/hn
    ZCfLA+6ni8eA2jJNTpswDP8y5KSumyPOaMh/qcbIcUR9m5GTA+KSWQ2mFl4dsb1i
    smRmGleTqpTCp9vfIAlickED1rT3lSS2Uj4lpfrWIQkDKvA7u6Iht9k/AoGBAOkS
    3xluryqZ3U4iHf1js/bL5ky5Jb5WZuSRbi5qS0ZohCWpr33zq7bwXBJfhF6t1cIT
    5OWLjRzQdn9mm14Nko9pcrfEyXcv4D+5AFgmtW8E8Cg86Dk7vmkHpcHH1Ctwnzr6
    /3i3x+ud6Koq/jGmITT6KXN5ao7Rq9p19GfwJYSvAoGBANQpdaBLFAOyU7f+e854
    Jt64g4/BWjZHHWNZffwB1qsCPdxmzvrWlb/pwO9TAjVZE1Qq06wfpwyopw1pIz+L
    DJdOMr20PJI3RmbTj8sDQRqWSFdkJL/m7gBMqZV7rgtG8zg0y9qck4lk1t3VYvbY
    7sFLZO+Z+HmnIUpYApG8Ed9tAoGAMGqZKcFSZfkcfdScgjyp78SfjKSRcJ6mNSj4
    yG+QP4oKmYBMUk/CBficR7zL1Jcr5msXi4+XurqbQw/fioQrQ9tV11LrvvSVEuet
    aKJx4iQWd2VfoDQG8+6AwmZubq+whCIL29nhj9J3uJHByDKIh2bIIZLBTfXES1dh
    dA3w3UUCgYEAi/SMFC25f4+tvEuG56gV7Jk37qQnEBSz9zO9NlpH9wzWlMQlvpiy
    0iWRpRacT6xbCl7EzECXCnAHo2WFDXFIl1m3oAEmpBes6X+wkEgJLQOyiUJCBziD
    8RcRnKdLJP/wYrFrtFOHnGIg5IeZO06JYIQweBfWb3qSXegveIUcrwY=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename: /etc/rails/keys/fiveguardoffense_production.key
      iv_filename:  /etc/rails/keys/fiveguardoffense_production.iv
      cipher_name:  aes-256-cbc
      # Base64 encode encrypted data without newlines
      encoding:     :base64strict
      version:      1
